/**
 * palette.ts — 12 data-driven palettes matching the original HTML renderer.
 * Each palette has 5 HSL-range slots: [hMin,hMax,sMin,sMax,lMin,lMax]
 * Colors are generated by sampling within ranges using a seeded RNG.
 * Slot roles: 0=DOM, 1=SEC, 2=ACC, 3=BLK, 4=WHT
 */

export type RGB = [number, number, number];

function hslToRgb(h: number, s: number, l: number): RGB {
  s /= 100; l /= 100;
  const k = (n: number) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return [Math.round(f(0) * 255), Math.round(f(8) * 255), Math.round(f(4) * 255)];
}

function sampleSlot(
  [hMin, hMax, sMin, sMax, lMin, lMax]: number[],
  rh: number, rs: number, rl: number,
): RGB {
  return hslToRgb(hMin + rh * (hMax - hMin), sMin + rs * (sMax - sMin), lMin + rl * (lMax - lMin));
}

/** rgba(r,g,b,alpha) helper */
export function rc([r, g, b]: RGB, a = 1): string {
  return `rgba(${r},${g},${b},${a})`;
}

/** XOR-shift seeded RNG — matches original */
function xorRng(seed: number) {
  let s = (seed >>> 0) || 1;
  return () => { s ^= s << 13; s ^= s >> 17; s ^= s << 5; return (s >>> 0) / 0xffffffff; };
}

interface PaletteDef {
  id: string;
  label: string;
  desc: string;
  slots: number[][];
  check: (errors: number, txns: number, posts: number, peakHour: number, glitchIndex: number) => boolean;
}

export const PALETTES: PaletteDef[] = [
  {
    id: 'INCIDENT', label: 'Incident', desc: 'High error rate (≥20 errors)',
    check: (err) => err >= 100,
    slots: [
      [0,15,90,100,45,65],
      [15,42,85,100,48,68],
      [68,95,85,100,45,68],
      [0,360,0,15,3,12],
      [0,20,0,18,88,97],
    ],
  },
  {
    id: 'GRAVEYARD', label: 'Graveyard', desc: 'Peak activity 00:00–05:59 UTC',
    check: (_e,_t,_p,ph) => ph <= 5,
    slots: [
      [255,285,80,100,22,50],
      [270,300,75,100,28,55],
      [175,210,70,100,40,68],
      [240,280,0,20,3,10],
      [200,230,0,22,88,96],
    ],
  },
  {
    id: 'SUNRISE', label: 'Sunrise', desc: 'Peak activity 06:00–09:59 UTC',
    check: (_e,_t,_p,ph) => ph >= 6 && ph <= 9,
    slots: [
      [10,38,90,100,48,70],
      [38,58,85,100,55,75],
      [240,270,55,80,20,42],
      [5,20,0,15,3,12],
      [35,60,0,20,88,97],
    ],
  },
  {
    id: 'DEFI', label: 'DeFi Day', desc: 'High txns (>350), low posts (<60)',
    check: (_e,t,p) => t > 350 && p < 60,
    slots: [
      [135,160,88,100,42,65],
      [195,225,80,100,40,65],
      [42,55,85,100,50,72],
      [0,360,0,12,3,10],
      [0,360,0,10,90,98],
    ],
  },
  {
    id: 'HYPERSOCIAL', label: 'Hypersocial', desc: 'Posts >100',
    check: (_e,_t,p) => p > 100,
    slots: [
      [295,325,88,100,42,65],
      [175,205,85,100,45,70],
      [50,70,85,100,52,72],
      [280,310,0,18,3,12],
      [290,320,0,20,88,97],
    ],
  },
  {
    id: 'TWILIGHT', label: 'Twilight', desc: 'Peak activity 19:00–23:59 UTC',
    check: (_e,_t,_p,ph) => ph >= 19,
    slots: [
      [265,295,85,100,32,58],
      [300,330,80,100,38,62],
      [185,210,65,90,45,68],
      [250,280,0,20,3,11],
      [270,300,0,22,88,96],
    ],
  },
  {
    id: 'MERIDIAN', label: 'Meridian', desc: 'Peak activity 10:00–14:59 UTC',
    check: (_e,_t,_p,ph) => ph >= 10 && ph <= 14,
    slots: [
      [195,220,88,100,44,68],
      [175,198,78,100,52,75],
      [22,42,80,100,48,70],
      [210,240,0,18,3,12],
      [190,215,0,18,88,97],
    ],
  },
  {
    id: 'GOLDEN_HOUR', label: 'Golden Hour', desc: 'Peak activity 15:00–18:59 UTC',
    check: (_e,_t,_p,ph) => ph >= 15 && ph <= 18,
    slots: [
      [35,55,90,100,48,70],
      [15,35,85,100,45,65],
      [255,285,60,88,28,52],
      [20,40,0,18,3,12],
      [42,58,0,18,88,97],
    ],
  },
  {
    id: 'BANKR', label: 'Bankr Mode', desc: 'Txn:Post ratio >6',
    check: (_e,t,p) => p > 0 && (t / p) > 6,
    slots: [
      [130,158,88,100,40,65],
      [0,15,80,100,42,62],
      [42,56,78,100,50,72],
      [0,360,0,10,3,9],
      [0,360,0,8,90,98],
    ],
  },
  {
    id: 'FARCASTER', label: 'Farcaster', desc: 'Post:Txn ratio >1.5',
    check: (_e,t,p) => t > 0 && (p / t) > 1.5,
    slots: [
      [258,280,78,100,32,58],
      [300,328,78,100,40,65],
      [185,208,65,92,45,70],
      [255,275,0,18,3,12],
      [265,285,0,22,88,97],
    ],
  },
  {
    id: 'DORMANT', label: 'Dormant', desc: 'Low activity',
    check: (_e,t,p) => t < 120 && p < 35,
    slots: [
      [200,225,25,52,28,48],
      [175,200,20,42,22,40],
      [30,50,15,35,35,55],
      [200,230,0,12,3,9],
      [200,220,0,12,88,96],
    ],
  },
  {
    id: 'SURGE', label: 'Surge', desc: 'Glitch index ≥85',
    check: (_e,_t,_p,_ph,gi) => gi >= 85,
    slots: [
      [0,360,88,100,50,78],
      [0,360,82,100,45,72],
      [0,360,0,8,90,99],
      [0,360,0,10,2,8],
      [0,360,85,100,55,82],
    ],
  },
];

/** Select palette ID from operational stats */
export function selectPaletteId(
  errors: number, txns: number, posts: number, peakHour: number, glitchIndex: number,
): string {
  for (const p of PALETTES) {
    if (p.check(errors, txns, posts, peakHour, glitchIndex)) return p.id;
  }
  return 'MERIDIAN';
}

/** Generate 5 RGB colors [DOM, SEC, ACC, BLK, WHT] from palette + seed */
export function generateColors(paletteId: string, seed: number): [RGB, RGB, RGB, RGB, RGB] {
  const pal = PALETTES.find(p => p.id === paletteId) ?? PALETTES[6]; // MERIDIAN fallback
  const rng = xorRng((seed ^ 0xc0a7d1a5) >>> 0);
  const colors = pal.slots.map(slot => sampleSlot(slot, rng(), rng(), rng()));
  return colors as [RGB, RGB, RGB, RGB, RGB];
}

/** Backward-compat shim for pipeline (returns string[] palette) */
export function selectPalette(dayLog: {
  errors?: number; txns?: number; posts?: number; peakHour?: number;
  glitchIndex?: number; dayNumber?: number;
}): { id: string; label: string; colors: string[] } {
  const errors = dayLog.errors ?? 0;
  const txns = dayLog.txns ?? 0;
  const posts = dayLog.posts ?? 0;
  const peakHour = dayLog.peakHour ?? 14;
  const glitchIndex = dayLog.glitchIndex ?? 0;
  const id = selectPaletteId(errors, txns, posts, peakHour, glitchIndex);
  const pal = PALETTES.find(p => p.id === id)!;
  const seed = dayLog.dayNumber ?? 1;
  const rgbs = generateColors(id, seed);
  return {
    id,
    label: pal.label,
    colors: rgbs.map(([r,g,b]) => `rgb(${r},${g},${b})`),
  };
}

export function computeGlitchIndex(stats: { errors?: number; txns?: number; messages?: number }): number {
  return Math.min(100, Math.max(0,
    (stats.errors ?? 0) * 3 + (stats.txns ?? 0) / 10 + (stats.messages ?? 0) / 100,
  ));
}
